### ISSUE TITLE
Can't get the "Create Widget" button from manage pages header

### ISSUE THREAD

**Issue by geogeorgejoseph** [sojimaxi/grav-plugin-widget#3]
I am using Grav v1.3.1 .I installed the widget plug-in and done the all the steps given in the "https://github.com/sojimaxi/grav-plugin-widget" . Cleared all cache.But I Can't get the "Create Widget" button from manage pages header section .Can you suggest a solution for this issue ?

**Comment by sojimaxi** [comment]
@geogeorgejoseph am using version 1.3.1 myself and it works well. The issue is the admin plugin. I will advise you upgrade to the latest `admin` plugin version , currently `v1.5.1`. I also raise this issue [#1149](https://github.com/getgrav/grav-plugin-admin/issues/1149) with them as well a while back when I experienced the same issue while in development.

**Comment by geogeorgejoseph** [comment]
thanks,now it's work fine...

**Comment by sojimaxi** [comment]
That's great.
